version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: Password#1234
      POSTGRES_DB: microservice_db
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: